# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 203952db3db76a589c7d53eb533a61bfd5f5d1c1ecbeed8948d3ff7235d7e5d5d49cd72c6e78914ccbf79ded0348f0afd911f4781180e5c9632185d284e95670
  api_key: rsg2ehj4293rcr9x794dv7zr
test:
  secret_key_base: 7c75d9160528fcc14685fa9310f4c7d9536321b904ee21903616f18b7a6b3baefa5890d3dff29e02d63456111a61db260c3b54a3e8702f8d7f6a5ff41d6e9b10

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
